[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/swvitaliy"
  weight = 99
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 999
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "archive"
  url = "https://old.swvit.com"


